version: '3.1'

services:
  database:
    container_name: postgres-msemail
    image: postgres
    ports:
      - '5434:5434'
    expose:
      - '5434'
    command: -p 5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco123
      POSTGRES_DB: ms-email
    networks:
      - default
    volumes:
      - /home/eduardo/docker/volumes/mseamil-postgres:/var/lib/postgresql/data

networks:
  default: