spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: duduxss3@gmail.com
    password: nwixuibblolbxaxh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5434/ms-email
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083