spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: duduxss3@gmail.com
    password: nwixuibblolbxaxh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5434/ms-email
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://ihtthkyn:AGXXBy6yE9ws_YUGPlSV5dPH6NxKuvkS@snake.rmq2.cloudamqp.com/ihtthkyn
    queue: ms.email


server:
  port: 8083